#########################
## ARCHIVE CONFIG FILE

ROOT:
    DEFAULT_RAFT_CONFIGURATION:
        raft00: ['ALL']
        raft01: ['ALL']
        raft10: ['ALL']
        raft20: ['ALL']
        raft30: ['ALL']
        raft40: ['ALL']
        raft01: ['ALL']
        raft11: ['ALL']
        raft21: ['ALL']
        raft31: ['ALL']
        raft41: ['ALL']
        raft02: ['ALL']
        raft12: ['ALL']
        raft22: ['ALL']
        raft32: ['ALL']
        raft42: ['ALL']
        raft03: ['ALL']
        raft13: ['ALL']
        raft23: ['ALL']
        raft33: ['ALL']
        raft43: ['ALL']
        raft04: ['ALL']
        raft14: ['ALL']
        raft24: ['ALL']
        raft34: ['ALL']
        raft44: ['ALL']

    CHECKSUM_ENABLED: no

    ARCHIVE_DIRECTORY_ROOT: /data/export/
  
