version: '3'
services:
    rabbitmq:
        image: rabbitmq:3.7.15
        container_name: iip_rabbitmq
        networks: 
            some-network:
                aliases:
                    - some-rabbit
        ports:
          - "5672:5672"
          - "15672:15672"
    lsst-dev:
        build:
          context: ../../
          dockerfile: ./etc/docker/development-Dockerfile
          args:
            - RABBITMQ_USER
            - RABBITMQ_PASSWD
        container_name: iip_dev
        volumes:
            - ../..:/app
        networks: 
          - some-network
        tty: true
networks:
    some-network:
