# Message Broker usr/passwd settings for system
ROOT:
  CFG_FILE_NAME: BrokerCredentials.yaml
  #
  # Broker user names and passwds
  # Why so many? To avoid broker connection 
  # contention, each publisher should have its
  # own connection. Some foremen, who message
  # between the base and ncsa, have extra sets
  BASE_BROKER_NAME: BASE
  BASE_BROKER_PASSWD: BASE
  BASE_BROKER_PUB_NAME: BASE_PUB
  BASE_BROKER_PUB_PASSWD: BASE_PUB

  AFM_BROKER_NAME: AFM
  AFM_BROKER_PASSWD: AFM
  AFM_BROKER_PUB_NAME: AFM_PUB
  AFM_BROKER_PUB_PASSWD: AFM_PUB

  AUX_BROKER_NAME: AUX
  AUX_BROKER_PASSWD: AUX
  AUX_BROKER_PUB_NAME: AUX_PUB
  AUX_BROKER_PUB_PASSWD: AUX_PUB

  PFM_BROKER_NAME: PFM
  PFM_BROKER_PASSWD: PFM
  PFM_BROKER_PUB_NAME: PFM_PUB
  PFM_BROKER_PUB_PASSWD: PFM_PUB
  #
  PFM_NCSA_BROKER_NAME: PFM_NCSA
  PFM_NCSA_BROKER_PASSWD: PFM_NCSA
  PFM_NCSA_BROKER_PUB_NAME: PFM_NCSA_PUB
  PFM_NCSA_BROKER_PUB_PASSWD: PFM_NCSA_PUB

  ARCHIVE_BROKER_NAME: ARCHIE
  ARCHIVE_BROKER_PASSWD: ARCHIE
  ARCHIVE_BROKER_PUB_NAME: ARCHIE_PUB
  ARCHIVE_BROKER_PUB_PASSWD: ARCHIE_PUB

  DMCS_BROKER_NAME: DMCS
  DMCS_BROKER_PASSWD: DMCS
  DMCS_BROKER_PUB_NAME: DMCS_PUB
  DMCS_BROKER_PUB_PASSWD: DMCS_PUB
  DMCS_FAULT_PUB_NAME: DMCS_FAULT_PUB
  DMCS_FAULT_PUB_PASSWD: DMCS_FAULT_PUB

  NCSA_BROKER_NAME: NCSA
  NCSA_BROKER_PASSWD: NCSA
  NCSA_BROKER_PUB_NAME: NCSA_PUB
  NCSA_BROKER_PUB_PASSWD: NCSA_PUB

  OCS_BROKER_NAME: OCS
  OCS_BROKER_PASSWD: OCS
  OCS_BROKER_PUB_NAME: OCS_PUB
  OCS_BROKER_PUB_PASSWD: OCS_PUB

  NFM_BASE_BROKER_NAME: NFM_BASE
  NFM_BASE_BROKER_PASSWD: NFM_BASE
  NFM_BASE_BROKER_PUB_NAME: NFM_BASE_PUB
  NFM_BASE_BROKER_PUB_PASSWD: NFM_BASE_PUB
  #
  NFM_NCSA_BROKER_NAME: NFM_NCSA
  NFM_NCSA_BROKER_PASSWD: NFM_NCSA
  NFM_NCSA_BROKER_PUB_NAME: NFM_NCSA_PUB
  NFM_NCSA_BROKER_PUB_PASSWD: NFM_NCSA_PUB

  AUDIT_BROKER_NAME: AUDIT
  AUDIT_BROKER_PASSWD: AUDIT
  NCSA_BROKER_NAME: NCSA
  NCSA_BROKER_PASSWD: NCSA
  NCSA_BROKER_PUB_NAME: NCSA_PUB
  NCSA_BROKER_PUB_PASSWD: NCSA_PUB
  NCSA_BROKER_CLSTR_PUB_NAME: NCSA_CLSTR_PUB
  NCSA_BROKER_CLSTR_PUB_PASSWD: NCSA_CLSTR_PUB
  BASE_BROKER_ADDR: 140.252.32.128:5672/%2ftest_at
  NCSA_BROKER_ADDR: 140.252.32.128:5672/%2ftest_at

  #END

