# Cfg settings for system
ROOT:
  CFG_FILE_NAME: FwdrDistAllocation.yaml

  XFER_COMPONENTS:
    ARCHIVE_FORWARDERS:
#      FORWARDER_1:
#        NAME: F1
#        HOSTNAME: lsst-wf-base01.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.181
#        STATE: IDLE
#        CONSUME_QUEUE: f1_consume
#        PUBLISH_QUEUE: ar_foreman_ack_publish
#
#      FORWARDER_99:
#        NAME: F99
#        HOSTNAME: lsst-daq.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.74
#        STATE: IDLE
#        CONSUME_QUEUE: f99_consume
#        PUBLISH_QUEUE: ar_foreman_ack_publish
#
#      FORWARDER_8:
#        NAME: F8
#        HOSTNAME: lsst-wf-base08.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.168
#        STATE: IDLE
#        CONSUME_QUEUE: f8_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_9:
#        NAME: F9
#        HOSTNAME: lsst-wf-base09.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.169
#        STATE: IDLE
#        CONSUME_QUEUE: f9_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_10:
#        NAME: F10
#        HOSTNAME: lsst-wf-base10.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.170
#        STATE: IDLE
#        CONSUME_QUEUE: f10_consume
#        PUBLISH_QUEUE: forwarder_publish
#
    AUX_FORWARDERS:
      FORWARDER_99:
        NAME: F99
        HOSTNAME: lsst-daq.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.74
        STATE: IDLE
        CONSUME_QUEUE: f99_consume
        PUBLISH_QUEUE: at_foreman_ack_publish

      FORWARDER_100:
        NAME: F100
        HOSTNAME: lsst-daq.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.74
        STATE: IDLE
        CONSUME_QUEUE: 100_consume
        PUBLISH_QUEUE: ar_foreman_ack_publish

#      FORWARDER_10:
#        NAME: F10
#        HOSTNAME: lsst-wf-base10.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.190
#        STATE: IDLE
#        CONSUME_QUEUE: f10_consume
#        PUBLISH_QUEUE: sp_foreman_ack_publish
#        DAQ: API


#    PP_FORWARDERS:
#      FORWARDER_1:
#        NAME: F1
#        HOSTNAME: lsst-wf-base01.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.161
#        STATE: IDLE
#        CONSUME_QUEUE: f1_consume
#        PUBLISH_QUEUE: pp_foreman_ack_publish
#
#      FORWARDER_2:
#        NAME: F2
#        HOSTNAME: lsst-wf-base02.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.162
#        STATE: IDLE
#        CONSUME_QUEUE: f2_consume
#        PUBLISH_QUEUE: pp_foreman_ack_publish
#
#      FORWARDER_3:
#        NAME: F3
#        HOSTNAME: lsst-wf-base03.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.163
#        STATE: IDLE
#        CONSUME_QUEUE: f3_consume
#        PUBLISH_QUEUE: pp_foreman_ack_publish
#
#      FORWARDER_4:
#        NAME: F4
#        HOSTNAME: lsst-wf-base04.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.164
#        STATE: IDLE
#        CONSUME_QUEUE: F4_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_5:
#        NAME: F5
#        HOSTNAME: lsst-wf-base05.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.165
#        STATE: IDLE
#        CONSUME_QUEUE: F5_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_6:
#        NAME: F6
#        HOSTNAME: lsst-wf-base06.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.166
#        STATE: IDLE
#        CONSUME_QUEUE: F6_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_7:
#        NAME: F7
#        HOSTNAME: lsst-wf-base07.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.167
#        STATE: IDLE
#        STATE: IDLE
#        STATE: IDLE
#        CONSUME_QUEUE: F7_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_8:
#        NAME: F8
#        HOSTNAME: lsst-wf-base08.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.168
#        STATE: IDLE
#        CONSUME_QUEUE: F8_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_9:
#        NAME: F9
#        HOSTNAME: lsst-wf-base09.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.169
#        STATE: IDLE
#        CONSUME_QUEUE: F9_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#      FORWARDER_10:
#        NAME: F10
#        HOSTNAME: lsst-wf-base10.ncsa.illinois.edu  
#        IP_ADDR: 141.142.238.170
#        STATE: IDLE
#        CONSUME_QUEUE: f10_consume
#        PUBLISH_QUEUE: forwarder_publish
#
#
    CATCHUP_FORWARDERS:
      FORWARDER_15:
        NAME: F15
        HOSTNAME: lsst-wf-base10.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.170
        STATE: IDLE
        CONSUME_QUEUE: F14_consume
        PUBLISH_QUEUE: forwarder_publish

####
#### Distributor List - Distributors located at the NCSA
####

    DISTRIBUTORS:
      DISTRIBUTOR_1:
        NAME: D1
        HOSTNAME: lsst-wf-dist01.ncsa.illinois.edu  
        IP_ADDR: 141.142.237.161
        CONSUME_QUEUE: d1_consume
        PUBLISH_QUEUE: distributor_publish
        TARGET_DIR: /home/D1/xfer_dir

      DISTRIBUTOR_2:
        NAME: D2
        HOSTNAME: lsst-wf-dist02.ncsa.illinois.edu  
        IP_ADDR: 141.142.237.162
        CONSUME_QUEUE: d2_consume
        PUBLISH_QUEUE: distributor_publish
        TARGET_DIR: /home/D2/xfer_dir

#      DISTRIBUTOR_3:
#        NAME: D3
#        HOSTNAME: lsst-wf-dist03.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.163
#        CONSUME_QUEUE: D3_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D3/xfer_dir
#
#      DISTRIBUTOR_4:
#        NAME: D4
#        HOSTNAME: lsst-wf-dist04.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.164
#        CONSUME_QUEUE: D4_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D4/xfer_dir
#
#      DISTRIBUTOR_5:
#        NAME: D5
#        HOSTNAME: lsst-wf-dist05.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.165
#        CONSUME_QUEUE: D5_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D5/xfer_dir
#
#      DISTRIBUTOR_6:
#        NAME: D6
#        HOSTNAME: lsst-wf-dist06.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.166
#        CONSUME_QUEUE: D6_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D6/xfer_dir
#
#      DISTRIBUTOR_7:
#        NAME: D7
#        HOSTNAME: lsst-wf-dist07.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.167
#        CONSUME_QUEUE: D7_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D7/xfer_dir
#
#      DISTRIBUTOR_8:
#        NAME: D8
#        HOSTNAME: lsst-wf-dist08.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.168
#        CONSUME_QUEUE: D8_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D8/xfer_dir
#
#      DISTRIBUTOR_9:
#        NAME: D9
#        HOSTNAME: lsst-wf-dist09.ncsa.illinois.edu  
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D9/xfer_dir
#
#      DISTRIBUTOR_10:
#        NAME: D10
#        HOSTNAME: lsst-wf-dist10.ncsa.illinois.edu  
#        IP_ADDR: 141.142.237.170
#        CONSUME_QUEUE: D10_consume
#        PUBLISH_QUEUE: distributor_publish
#        TARGET_DIR: /home/D10/xfer_dir

