# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-08 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(max_length=50)),
                ('visit', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('job_pairs', models.CharField(max_length=50)),
                ('image_id', models.CharField(max_length=50)),
                ('measurement', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('job', models.CharField(max_length=50)),
            ],
        ),
    ]
