# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 15:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='job',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='job_pairs',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='session',
        ),
    ]
