# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-09 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0002_auto_20170609_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='forwarder_id',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machines',
            name='session',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
