# Cfg settings for system
ROOT:
  NUMBER_OF_PAIRS: 10

  # Broker user names and passwds
  # Why so many? To avoid broker connection 
  # contention, each publisher should have its
  # own connection. Some foremen, who message
  # between the base and ncsa, have extra sets
  BASE_BROKER_NAME: BASE
  BASE_BROKER_PASSWD: BASE
  BASE_BROKER_PUB_NAME: BASE_PUB
  BASE_BROKER_PUB_PASSWD: BASE_PUB

  AFM_BROKER_NAME: AFM
  AFM_BROKER_PASSWD: AFM
  AFM_BROKER_PUB_NAME: AFM_PUB
  AFM_BROKER_PUB_PASSWD: AFM_PUB

  AUX_BROKER_NAME: AUX
  AUX_BROKER_PASSWD: AUX
  AUX_BROKER_PUB_NAME: AUX_PUB
  AUX_BROKER_PUB_PASSWD: AUX_PUB

  PFM_BROKER_NAME: PFM
  PFM_BROKER_PASSWD: PFM
  PFM_BROKER_PUB_NAME: PFM_PUB
  PFM_BROKER_PUB_PASSWD: PFM_PUB
  #
  PFM_NCSA_BROKER_NAME: PFM_NCSA
  PFM_NCSA_BROKER_PASSWD: PFM_NCSA
  PFM_NCSA_BROKER_PUB_NAME: PFM_NCSA_PUB
  PFM_NCSA_BROKER_PUB_PASSWD: PFM_NCSA_PUB

  ARCHIVE_BROKER_NAME: ARCHIE
  ARCHIVE_BROKER_PASSWD: ARCHIE
  ARCHIVE_BROKER_PUB_NAME: ARCHIE_PUB
  ARCHIVE_BROKER_PUB_PASSWD: ARCHIE_PUB

  DMCS_BROKER_NAME: DMCS
  DMCS_BROKER_PASSWD: DMCS
  DMCS_BROKER_PUB_NAME: DMCS_PUB
  DMCS_BROKER_PUB_PASSWD: DMCS_PUB
  DMCS_FAULT_PUB_NAME: DMCS_FAULT_PUB
  DMCS_FAULT_PUB_PASSWD: DMCS_FAULT_PUB

  NCSA_BROKER_NAME: NCSA
  NCSA_BROKER_PASSWD: NCSA
  NCSA_BROKER_PUB_NAME: NCSA_PUB
  NCSA_BROKER_PUB_PASSWD: NCSA_PUB

  OCS_BROKER_NAME: OCS
  OCS_BROKER_PASSWD: OCS
  OCS_BROKER_PUB_NAME: OCS_PUB
  OCS_BROKER_PUB_PASSWD: OCS_PUB

  NFM_BASE_BROKER_NAME: NFM_BASE
  NFM_BASE_BROKER_PASSWD: NFM_BASE
  NFM_BASE_BROKER_PUB_NAME: NFM_BASE_PUB
  NFM_BASE_BROKER_PUB_PASSWD: NFM_BASE_PUB
  
  NFM_NCSA_BROKER_NAME: NFM_NCSA
  NFM_NCSA_BROKER_PASSWD: NFM_NCSA
  NFM_NCSA_BROKER_PUB_NAME: NFM_NCSA_PUB
  NFM_NCSA_BROKER_PUB_PASSWD: NFM_NCSA_PUB

  AUDIT_BROKER_NAME: AUDIT
  AUDIT_BROKER_PASSWD: AUDIT
  NCSA_BROKER_NAME: NCSA
  NCSA_BROKER_PASSWD: NCSA
  NCSA_BROKER_PUB_NAME: NCSA_PUB
  NCSA_BROKER_PUB_PASSWD: NCSA_PUB
  NCSA_BROKER_CLSTR_PUB_NAME: NCSA_CLSTR_PUB
  NCSA_BROKER_CLSTR_PUB_PASSWD: NCSA_CLSTR_PUB
  BASE_BROKER_ADDR: 141.142.238.10:5672/%2ftest_at
  NCSA_BROKER_ADDR: 140.252.32.128:5672/%2ftest_at
  INFLUX_DB: L1_Test
  SESSION_ID_FILE: "/var/session_id"
  DMCS_ACK_ID_FILE: "/var/dmcs_ack_id"
  AUDIT_MSG_FORMAT: YAML
  USE_MUTEX: YES
  #AR_CFG_KEYS: ['7FC7','2321A','AC11']
  #AR_CFG_KEYS: Normal
  #AR_CFG_KEYS: archiver-Normal
  #PP_CFG_KEYS: processingcluster-Normal
  AR_CFG_KEYS: Normal
  PP_CFG_KEYS: Normal
  CU_CFG_KEYS: Normal
  AT_CFG_KEYS: Normal
  #CU_CFG_KEYS: catchuparchiver-Normal
  DMCS_FAULT_QUEUE: dmcs_fault_consume
  DEFAULT_RAFT_CONFIGURATION:
#    raft00: ['ALL'] 
#    raft01: ['11'] 
#    raft10: ['11'] 
#    raft20: ['00','12','22'] 
#    raft30: ['00','01','02','11','12','22','10']
#    raft40: ['ALL'] 
#    raft01: ['11'] 
#    raft11: ['12','22'] 
#    raft21: ['ALL'] 
#    raft31: ['ALL'] 
#    raft41: ['ALL'] 
    raft02: ['00'] 
#    raft12: ['ALL'] 
#    raft22: ['ALL'] 
#    raft32: ['ALL'] 
#    raft42: ['ALL'] 
#    raft03: ['ALL'] 
#    raft13: ['ALL'] 
#    raft23: ['ALL'] 
#    raft33: ['ALL'] 
#    raft43: ['ALL'] 
#    raft04: ['ALL'] 
#    raft14: ['ALL'] 
#    raft24: ['ALL'] 
#    raft34: ['ALL'] 
#    raft44: ['ALL'] 
  RAFT_LIST:  ['4','6','18','2','1','20','15','16','3','12','5','10','9','14','19','7','13','8','21','17','11']
  CCD_LIST:  ['34','6','160','161','162','163','181','2','1','20','115']
  #CCD_LIST:  ['34','6','160','161','162','163','181','2','1','20','115','136','3','12','50','101','79','144','19','7','139','8','21','172','11','121','122','123','124','125','126','127','128','129','130','131','132','133','134','135','137','138','143']  #43
  GENERAL_SETTINGS:
    TsXmlVersion: ManCtrl_MPD_AuxTel 
    TsSALVersion: 3.7.1
    L1DMRepoTag: V1.4a-ats_turnkey_system
  FOREMAN_CONSUME_QUEUES:
    AR: ar_foreman_consume
    PP: pp_foreman_consume
    CU: cu_foreman_consume
    AT: at_foreman_consume
  ARCHIVE:
    USE_ARCHIVE_CTRL: True
    ARCHIVE_NAME: ARC
    ARCHIVE_LOGIN: ARC
    ARCHIVE_IP: 140.252.32.128
    ARCHIVE_HOSTNAME: ARC
    ARCHIVE_XFER_ROOT: /data/export
    ARCHIVE_AT_XFER_ROOT: /data/export
    #ARCHIVE_AT_XFER_ROOT: /data/export/DM_Test
    ARCHIVE_AR_XFER_ROOT: /data/export
    CHECKSUM_ENABLED: no  
    CHECKSUM_TYPE: MD5   # Current available options: MD5, CRC-32 
  EFD:
    EFD_NAME: LFA
    EFD_LOGIN: felipe
    EFD_IP: 141.142.238.177
    EFD_HOSTNAME: ARCHIE
    EFD_XFER_ROOT: /mnt/lfa/
    CHECKSUM_ENABLED: no
  ATS:
    WFS_RAFT: ats
    WFS_CCD: wfs_ccd
  OCS: 
    OCS_NAME: OCS
    OCS_PASSWD: OCS
    OCS_PUBLISH: ocs_dmcs_consume
    OCS_CONSUME: dmcs_ocs_publish
  STARTUP:
    AT_START_ENABLE: no
    AR_START_ENABLE: no
    PP_START_ENABLE: no
    CU_START_ENABLE: no
  SCOREBOARDS:
    AR_JOB_SCBD: 0
    AR_FWD_SCBD: 1
    AR_ACK_SCBD: 2
    PP_JOB_SCBD: 3
    PP_FWD_SCBD: 4
    PP_ACK_SCBD: 5
    CU_JOB_SCBD: 6
    CU_FWD_SCBD: 7
    CU_ACK_SCBD: 8
    SP_JOB_SCBD: 9
    SP_FWD_SCBD: 10
    SP_ACK_SCBD: 11
    NCSA_JOB_SCBD: 9
    NCSA_DIST_SCBD: 10
    NCSA_ACK_SCBD: 11
    DMCS_ACK_SCBD: 12
    DMCS_INCR_SCBD: 2
    DMCS_STATE_SCBD: 13
    DMCS_JOB_SCBD: 14
    DMCS_BACKLOG_SCBD: 15
    ARC_CTRL_ACK_SCBD: 16
    #ARC_CTRL_RCPT_SCBD: 17
    ARC_CTRL_RCPT_SCBD: 6
  POLICY:
    MAX_CCDS_PER_FWDR: 10
  XFER_COMPONENTS:
    FWDR_DIR_PREFIX: /tmp/gunk/

    ARCHIVE_FORWARDERS:
      FORWARDER_99:
        NAME: F99
        HOSTNAME: lsst-daq.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.74
        STATE: IDLE
        CONSUME_QUEUE: f99_consume
        PUBLISH_QUEUE: ar_foreman_ack_publish

    AUX_FORWARDERS:
      FORWARDER_99:
        NAME: F99
        HOSTNAME: lsst-daq.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.74
        STATE: IDLE
        CONSUME_QUEUE: f99_consume
        PUBLISH_QUEUE: at_foreman_ack_publish

      FORWARDER_100:
        NAME: F100
        HOSTNAME: lsst-daq.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.74
        STATE: IDLE
        CONSUME_QUEUE: 100_consume
        PUBLISH_QUEUE: ar_foreman_ack_publish

    CATCHUP_FORWARDERS:
      FORWARDER_15:
        NAME: F15
        HOSTNAME: lsst-wf-base10.ncsa.illinois.edu  
        IP_ADDR: 141.142.238.170
        STATE: IDLE
        CONSUME_QUEUE: F14_consume
        PUBLISH_QUEUE: forwarder_publish

    DISTRIBUTORS:
      DISTRIBUTOR_1:
        NAME: D1
        HOSTNAME: lsst-wf-dist01.ncsa.illinois.edu  
        IP_ADDR: 141.142.237.161
        CONSUME_QUEUE: d1_consume
        PUBLISH_QUEUE: distributor_publish
        TARGET_DIR: /home/D1/xfer_dir

      DISTRIBUTOR_2:
        NAME: D2
        HOSTNAME: lsst-wf-dist02.ncsa.illinois.edu  
        IP_ADDR: 141.142.237.162
        CONSUME_QUEUE: d2_consume
        PUBLISH_QUEUE: distributor_publish
        TARGET_DIR: /home/D2/xfer_dir
