SLEEP_TIMER: 5
BASE_BROKER_ADDR: 141.142.238.10:5672
VHOST: test_at

JOB_NUM: job_test
SESSION_ID: session_test
VISIT_ID: visit_test

HEADER_FILE: http://localhost:8000/test.header

IMAGES: 
    - IMAGE_ID: AT_O_20190405_000028
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1

PARTITION:
    AT:
        RAFT: [ ats ]
        CCD: [[ 00 ]] 

ARCHIVE:
    AT:
        IP: 141.142.238.15
        NAME: ARCHIE
        XFER_ROOT: /data/export

FORWARDERS:
    - NAME: FORWARDER_99 # changed to match with the forwarder key
      HOSTNAME: lsst-daq.ncsa.illinois.edu  
      IP_ADDR: 141.142.238.74
      STATE: IDLE
      CONSUME_QUEUE: f99_consume
      PUBLISH_QUEUE: at_foreman_ack_publish
