SLEEP_TIMER: 5
BASE_BROKER_ADDR: 10.0.100.128:5672
VHOST: test_at

JOB_NUM: job_test
SESSION_ID: session_test
VISIT_ID: visit_test

HEADER_FILE: http://localhost:8000/test.header

IMAGES: 
    - IMAGE_ID: AT_O_20190405_000028
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000070
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000071
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000072
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000073
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000074
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000075
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000076
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000077
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000078
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000079
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000080
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000081
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000082
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000083
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000084
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000085
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000086
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000087
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190405_000088
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1
    - IMAGE_ID: AT_O_20190408_000001
      IMAGE_INDEX: 0
      IMAGE_SEQUENCE_NAME: img_seq_test
      IMAGES_IN_SEQUENCE: 1

PARTITION:
    AT:
        RAFT: [ ats ]
        CCD: [[ 00 ]] 

ARCHIVE:
    AT:
        IP: 10.0.100.128
        NAME: ARC
        XFER_ROOT: /data/export/hwin16_test

FORWARDERS:
    - NAME: FORWARDER_99 # changed to match with the forwarder key
      HOSTNAME: lsst-daq.ncsa.illinois.edu  
      IP_ADDR: 10.0.100.129
      STATE: IDLE
      CONSUME_QUEUE: f99_consume
      PUBLISH_QUEUE: at_foreman_ack_publish
